Repository APPSCHOOL2-Android/FinalProject-ShoppingMallService-team1, pull requests merged in 2023-08, with the labels that each got.

#8 [FIX] logo gif 파일 변경
  Ipet_customer/app/src/main/res/drawable/logo_ipet.gif
Labels: FIx

#9 [FEAT] Splash 구현
  Ipet_customer/app/build.gradle
  Ipet_customer/app/src/main/AndroidManifest.xml
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/MainActivity.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/MainActivity.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/PermissionFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/viewmodel/MainViewModel.kt
  Ipet_customer/app/src/main/res/drawable/ic_account_circle_48dp.xml
  Ipet_customer/app/src/main/res/drawable/ic_check_box_24dp.xml
  Ipet_customer/app/src/main/res/drawable/ic_favorite_48dp.xml
  Ipet_customer/app/src/main/res/drawable/ic_groups_24dp.xml
  Ipet_customer/app/src/main/res/drawable/ic_home_24dp.xml
  Ipet_customer/app/src/main/res/drawable/ic_rate_review_48dp.xml
  Ipet_customer/app/src/main/res/drawable/ic_sale_outline_24dp.xml
  Ipet_customer/app/src/main/res/drawable/ic_search_24dp.xml
  Ipet_customer/app/src/main/res/drawable/ic_sell_24dp.xml
  Ipet_customer/app/src/main/res/drawable/ic_shopping_cart_48dp.xml
  Ipet_customer/app/src/main/res/drawable/logo_ipet.gif
  Ipet_customer/app/src/main/res/layout/activity_main.xml
  Ipet_customer/app/src/main/res/layout/fragment_permission.xml
  Ipet_customer/app/src/main/res/raw/raw_cat.json
  Ipet_customer/app/src/main/res/raw/raw_deliver_box.json
  Ipet_customer/app/src/main/res/raw/raw_dog.json
  Ipet_customer/app/src/main/res/raw/raw_dog_footprint.json
  Ipet_customer/app/src/main/res/raw/raw_ipet_logo.json
  Ipet_customer/app/src/main/res/raw/raw_payment_success.json
  Ipet_customer/app/src/main/res/raw/raw_sale.json
  Ipet_customer/app/src/main/res/raw/raw_shopping_bag.json
  Ipet_customer/app/src/main/res/values/colors.xml
  Ipet_customer/app/src/main/res/values/strings.xml
  Ipet_customer/app/src/main/res/values/themes.xml
Labels: Feature

#10 [Fix] logo 반복 재생 제거된 gif 파일로 수정
  Ipet_customer/app/src/main/res/drawable/logo_ipet.gif
Labels: FIx

#15 [Design] Typography 추가
  Ipet_customer/app/src/main/AndroidManifest.xml
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainViewModel.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/permission/PermissionFragment.kt
  Ipet_customer/app/src/main/res/layout/activity_main.xml
  Ipet_customer/app/src/main/res/layout/fragment_permission.xml
  Ipet_customer/app/src/main/res/values/typography.xml
Labels: UI

#19 [Feat] 권한 설정 구현
  Ipet_customer/app/src/main/AndroidManifest.xml
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/onboarding/OnboardFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/permission/PermissionFragment.kt
  Ipet_customer/app/src/main/res/drawable/shape_rect.xml
  Ipet_customer/app/src/main/res/layout/fragment_onboard.xml
  Ipet_customer/app/src/main/res/layout/fragment_permission.xml
  Ipet_customer/app/src/main/res/values/strings.xml
Labels: Feature

#28 [Feat] 온보딩 구현
  Ipet_customer/app/build.gradle
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/db/local/DataStoreDataSource.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/OnboardingRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainViewModel.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainViewModelFactory.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/onboarding/OnboardFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/onboarding/OnboardingPageFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/onboarding/OnboardingViewModel.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/onboarding/OnboardingViewModelFactory.kt
  Ipet_customer/app/src/main/res/drawable/selector_tab_dot.xml
  Ipet_customer/app/src/main/res/drawable/shape_default_indicator_dot.xml
  Ipet_customer/app/src/main/res/drawable/shape_indicator_dot_rose100.xml
  Ipet_customer/app/src/main/res/drawable/shape_rect_radius_20dp.xml
  Ipet_customer/app/src/main/res/layout/fragment_on_boarding_page.xml
  Ipet_customer/app/src/main/res/layout/fragment_onboard.xml
  Ipet_customer/app/src/main/res/values/strings.xml
Labels: Feature

#31 [Design] 권한 설정 및 온보딩 글씨 수정
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/onboarding/OnboardFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/onboarding/OnboardingPageFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/permission/PermissionFragment.kt
  Ipet_customer/app/src/main/res/layout/fragment_onboarding.xml
  Ipet_customer/app/src/main/res/layout/fragment_onboarding_page.xml
  Ipet_customer/app/src/main/res/layout/fragment_permission.xml
Labels: UI

#32 [Feat] 카카오 로그인 기능 구현 #13
  Ipet_customer/app/build.gradle
  Ipet_customer/app/src/main/AndroidManifest.xml
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/login/GlobalApplication.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/login/LoginFragment.kt
  Ipet_customer/buildSrc/src/main/kotlin/Versions.kt
  Ipet_customer/settings.gradle
Labels: Feature, Setting

#33 [Feat] 상품 상세 화면 구현
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
  Ipet_customer/app/src/main/res/layout/fragment_product_info.xml
  Ipet_customer/app/src/main/res/values/typography.xml
Labels: Feature, UI

#35 [Feat] 내 정보 화면 구현 #30
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/userinfo/UserInfoMainFragment.kt
  Ipet_customer/app/src/main/res/layout/fragment_user_info_main.xml
Labels: UI

#37 [Feat] 네이버 로그인 기능 구현 #13
  Ipet_customer/app/build.gradle
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/login/GlobalApplication.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/login/LoginFragment.kt
  Ipet_customer/buildSrc/src/main/kotlin/Versions.kt
Labels: Feature, Setting

#38 [Fix] Android 12 이전 버전 splash 적용
  Ipet_customer/app/build.gradle
  Ipet_customer/app/src/main/AndroidManifest.xml
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainViewModel.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/splash/SplashActivity.kt
  Ipet_customer/app/src/main/res/drawable/img_logo_ipet.xml
  Ipet_customer/app/src/main/res/layout/activity_splash.xml
  Ipet_customer/app/src/main/res/values/themes.xml
  Ipet_customer/buildSrc/src/main/kotlin/Versions.kt
Labels: FIx

#41 [Feat] 리뷰 작성 화면 구현
  Ipet_customer/app/src/main/AndroidManifest.xml
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/review/ReviewWriteFragment.kt
  Ipet_customer/app/src/main/res/drawable/ic_camera_24dp.xml
  Ipet_customer/app/src/main/res/drawable/ic_gallery_24dp.xml
  Ipet_customer/app/src/main/res/layout/fragment_review_write.xml
  Ipet_customer/app/src/main/res/xml/file_path.xml
Labels: Feature, UI

#44 [Feat] 찜 목록 화면 구현
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/heart/HeartFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/res/layout/fragment_heart.xml
  Ipet_customer/app/src/main/res/layout/item_heart_list.xml
Labels: UI

#46 [Feat] 쿠폰 화면 구현
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/model/Coupon.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/coupon/CouponAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/coupon/CouponFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/res/drawable/shape_coupon.xml
  Ipet_customer/app/src/main/res/drawable/shape_dash.xml
  Ipet_customer/app/src/main/res/layout/fragment_coupon.xml
  Ipet_customer/app/src/main/res/layout/item_coupon.xml
  Ipet_customer/app/src/main/res/values/strings.xml
Labels: Feature

#47 [Fix] 카카오 로그인 오류 수정 #13
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/login/GlobalApplication.kt
Labels: FIx

#49 [Chore] 파이어베이스 plugins 추가
  Ipet_customer/app/build.gradle
  Ipet_customer/build.gradle
  Ipet_seller/app/build.gradle
  Ipet_seller/build.gradle
Labels: Chore

#58 [Feat] 홈 화면 UI 구현
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/res/drawable/img_cat_icon.png
  Ipet_customer/app/src/main/res/drawable/img_dog_icon.png
  Ipet_customer/app/src/main/res/layout/fragment_home.xml
  Ipet_customer/app/src/main/res/layout/item_joint_product.xml
  Ipet_customer/app/src/main/res/layout/item_product_best.xml
  Ipet_customer/app/src/main/res/menu/toolbar_menu.xml
  Ipet_customer/app/src/main/res/values/themes.xml
Labels: Feature, UI

#59 [Feat] 로그인 예외 추가
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/db/remote/SellerDataSource.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/login/LoginFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/login/LoginViewModel.kt
Labels: Feature

#60 [Feat] 판매자용 회원가입 구현
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/db/remote/SellerDataSource.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/repository/SellerRepository.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/signup/SignupFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/signup/SignupViewModel.kt
  Ipet_seller/app/src/main/res/drawable/ic_error_outline_24.xml
  Ipet_seller/app/src/main/res/layout/fragment_signup.xml
  Ipet_seller/app/src/main/res/values/strings.xml
Labels: Feature, UI

#72 [Feat] 홈화면에서의 화면 이동 구현
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeBestAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeJointAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductListFragment.kt
Labels: Feature

#73 [Fix] 아이디가 소문자 1개, 숫자 1개가 포함되어 있지 않은 경우 회원가입 되는 부분 수정 #51
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/signup/SignupFragment.kt
Labels: FIx

#81 [Feat] 판매자용 상품 리스트 화면 구현
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/main/MainActivity.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/product/ProductListAdapter.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/product/ProductListFragment.kt
  Ipet_seller/app/src/main/res/layout/fragment_product_list.xml
  Ipet_seller/app/src/main/res/layout/item_productlist.xml
  Ipet_seller/app/src/main/res/menu/menu_productlist.xml
Labels: Feature, UI

#85 [Feature] 판매자용 홈 구현
  Ipet_seller/app/build.gradle
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/constant/CollectionId.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/db/local/DataStoreDataSource.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/db/remote/OrderDataSource.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/model/Order.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/repository/OrderRepository.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/repository/SellerRepository.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/home/HomeFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/home/HomeViewModel.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/home/HomeViewModelFactory.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/login/LoginFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/login/LoginViewModel.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/login/LoginViewModelFactory.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/signup/SignupFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/signup/SignupViewModel.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/signup/SignupViewModelFactory.kt
  Ipet_seller/app/src/main/res/drawable/ic_arrow_forward_ios_24dp.xml
  Ipet_seller/app/src/main/res/drawable/ic_error_outline_24dp.xml
  Ipet_seller/app/src/main/res/layout/fragment_home.xml
  Ipet_seller/app/src/main/res/layout/fragment_signup.xml
  Ipet_seller/app/src/main/res/values/strings.xml
  Ipet_seller/buildSrc/src/main/kotlin/Versions.kt
Labels: Feature, UI

#86 [Feature] 판매자용 판매상품 등록 구현
  Ipet_seller/app/src/main/AndroidManifest.xml
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/main/MainActivity.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/registration/RegistrationFragment.kt
  Ipet_seller/app/src/main/res/drawable/ic_add_photo_alternate_24px.xml
  Ipet_seller/app/src/main/res/drawable/ic_save_24px.xml
  Ipet_seller/app/src/main/res/layout/fragment_registration.xml
  Ipet_seller/app/src/main/res/menu/menu_registration.xml
Labels: Feature, UI

#87 [Feat] 앱 아이콘 추가
  Ipet_customer/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Ipet_customer/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  Ipet_customer/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Ipet_customer/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Ipet_customer/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  Ipet_customer/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Ipet_customer/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Ipet_customer/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  Ipet_customer/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Ipet_customer/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Ipet_customer/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  Ipet_customer/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Ipet_customer/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Ipet_customer/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  Ipet_customer/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Ipet_customer/app/src/main/res/values/themes.xml
  Ipet_seller/app/build.gradle
  Ipet_seller/app/src/main/AndroidManifest.xml
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/main/MainActivity.kt
  Ipet_seller/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Ipet_seller/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  Ipet_seller/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Ipet_seller/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Ipet_seller/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  Ipet_seller/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Ipet_seller/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Ipet_seller/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  Ipet_seller/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Ipet_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Ipet_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  Ipet_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Ipet_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Ipet_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  Ipet_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Ipet_seller/app/src/main/res/values/themes.xml
Labels: Feature

#89 [Fix] 누락된 앱 아이콘 추가
  Ipet_customer/app/src/main/AndroidManifest.xml
  Ipet_customer/app/src/main/ic_launcher_logo-playstore.png
  Ipet_customer/app/src/main/res/mipmap-anydpi-v26/ic_launcher_logo.xml
  Ipet_customer/app/src/main/res/mipmap-anydpi-v26/ic_launcher_logo_round.xml
  Ipet_customer/app/src/main/res/mipmap-hdpi/ic_launcher_logo.png
  Ipet_customer/app/src/main/res/mipmap-hdpi/ic_launcher_logo_foreground.png
  Ipet_customer/app/src/main/res/mipmap-hdpi/ic_launcher_logo_round.png
  Ipet_customer/app/src/main/res/mipmap-mdpi/ic_launcher_logo.png
  Ipet_customer/app/src/main/res/mipmap-mdpi/ic_launcher_logo_foreground.png
  Ipet_customer/app/src/main/res/mipmap-mdpi/ic_launcher_logo_round.png
  Ipet_customer/app/src/main/res/mipmap-xhdpi/ic_launcher_logo.png
  Ipet_customer/app/src/main/res/mipmap-xhdpi/ic_launcher_logo_foreground.png
  Ipet_customer/app/src/main/res/mipmap-xhdpi/ic_launcher_logo_round.png
  Ipet_customer/app/src/main/res/mipmap-xxhdpi/ic_launcher_logo.png
  Ipet_customer/app/src/main/res/mipmap-xxhdpi/ic_launcher_logo_foreground.png
  Ipet_customer/app/src/main/res/mipmap-xxhdpi/ic_launcher_logo_round.png
  Ipet_customer/app/src/main/res/mipmap-xxxhdpi/ic_launcher_logo.png
  Ipet_customer/app/src/main/res/mipmap-xxxhdpi/ic_launcher_logo_foreground.png
  Ipet_customer/app/src/main/res/mipmap-xxxhdpi/ic_launcher_logo_round.png
  Ipet_customer/app/src/main/res/values/ic_launcher_logo_background.xml
  Ipet_customer/app/src/main/res/values/themes.xml
  Ipet_seller/app/src/main/AndroidManifest.xml
  Ipet_seller/app/src/main/ic_launcher_logo-playstore.png
  Ipet_seller/app/src/main/res/mipmap-anydpi-v26/ic_launcher_logo.xml
  Ipet_seller/app/src/main/res/mipmap-anydpi-v26/ic_launcher_logo_round.xml
  Ipet_seller/app/src/main/res/mipmap-hdpi/ic_launcher_logo.png
  Ipet_seller/app/src/main/res/mipmap-hdpi/ic_launcher_logo_foreground.png
  Ipet_seller/app/src/main/res/mipmap-hdpi/ic_launcher_logo_round.png
  Ipet_seller/app/src/main/res/mipmap-mdpi/ic_launcher_logo.png
  Ipet_seller/app/src/main/res/mipmap-mdpi/ic_launcher_logo_foreground.png
  Ipet_seller/app/src/main/res/mipmap-mdpi/ic_launcher_logo_round.png
  Ipet_seller/app/src/main/res/mipmap-xhdpi/ic_launcher_logo.png
  Ipet_seller/app/src/main/res/mipmap-xhdpi/ic_launcher_logo_foreground.png
  Ipet_seller/app/src/main/res/mipmap-xhdpi/ic_launcher_logo_round.png
  Ipet_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher_logo.png
  Ipet_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher_logo_foreground.png
  Ipet_seller/app/src/main/res/mipmap-xxhdpi/ic_launcher_logo_round.png
  Ipet_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_logo.png
  Ipet_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_logo_foreground.png
  Ipet_seller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_logo_round.png
  Ipet_seller/app/src/main/res/values/ic_launcher_logo_background.xml
  Ipet_seller/app/src/main/res/values/themes.xml
Labels: FIx

#92 [Feat] 쿠폰 툴바 뒤로 가기 버튼 추가
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/coupon/CouponFragment.kt
  Ipet_seller/app/build.gradle
  Ipet_seller/buildSrc/src/main/kotlin/Versions.kt
  Ipet_seller/settings.gradle
Labels: Feature

#93 [Feat] 공동 구매 상품 recyclerView Firestore 연결 #45
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/model/Joint.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/JointRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeJointAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeViewModel.kt
Labels: Feature

#95 [Feat] 판매 매출 관리 화면 구현
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/constant/CollectionId.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/db/remote/ProductDataSource.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/model/Order.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/model/Product.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/model/Revenue.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/repository/ProductRepository.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/home/HomeFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/main/MainActivity.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/revenue/RevenueFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/revenue/RevenueViewModel.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/revenue/RevenueViewModelFactory.kt
  Ipet_seller/app/src/main/res/layout/fragment_revenue.xml
  Ipet_seller/app/src/main/res/values/strings.xml
Labels: Feature

#96 [Feat] 로그인 정보 저장 기능 구현
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/db/remote/CustomerDataSource.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/model/Customer.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/LoginRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/login/LoginFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/login/LoginViewModel.kt
Labels: Feature

#97 [Feat] 화면 회전 방지
  Ipet_customer/app/src/main/AndroidManifest.xml
  Ipet_seller/app/src/main/AndroidManifest.xml
Labels: Feature

#99 [Feat] 판매자용 화면 전환
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/home/HomeFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/product/ProductListFragment.kt
  Ipet_seller/app/src/main/res/layout/fragment_home.xml
Labels: Feature

#100 [Feat] 카카오 로그인 예외 처리
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/login/LoginFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/login/LoginViewModel.kt
Labels: Feature

#101 [Feat] 홈화면 베스트 상품 recyclerView Firestore 연결 및 필터링
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/model/Order.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/model/Product.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/BestProductRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeBestAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeJointAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeViewModel.kt
Labels: Feature

#103 [Design] 결제 완료 아이콘을 ImageView에서 Lottie로 수정 #52
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/payment/PaymentCompleteFragment.kt
  Ipet_customer/app/src/main/res/layout/fragment_payment_complete.xml
Labels: UI

#105 [Feat] recyclerView 상품 클릭 시 bundle 생성 및 전달
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/OrderRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/ProductRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeBestAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeJointAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeViewModel.kt
Labels: Feature

#108 [FIx] 바텀 네비게이션 바 아이콘 색상, 라벨 수정 #79
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/res/color/selector_bottom_navigation.xml
  Ipet_customer/app/src/main/res/color/selector_no_ripple.xml
  Ipet_customer/app/src/main/res/layout/activity_main.xml
  Ipet_customer/app/src/main/res/menu/bottomnavibar_menu.xml
Labels: FIx

#109 [Feat] 로그인 메서드 모듈화
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/LoginRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/login/LoginFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/login/LoginViewModel.kt
Labels: Feature

#110 [Feat] bundle 값을 받아 데이터 검색 후 가져오기 구현 #16
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/ProductRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/main/MainActivity.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoViewModel.kt
Labels: Feature

#114 [Fix] itemView 사진 수정 #80
  Ipet_seller/app/src/main/res/layout/item_productlist.xml
Labels: Feature

#117 [Feat] 판매 매출 관리 스켈레톤 UI 적용 #88
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/revenue/RevenueFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/revenue/RevenueViewModel.kt
  Ipet_seller/app/src/main/res/layout/fragment_revenue.xml
  Ipet_seller/app/src/main/res/layout/item_chart_loading.xml
Labels: Feature

#118 [Feat] RecyclerView Adapter에 Product 데이터 적용, 등록 상품 삭제 #81
  Ipet_seller/app/build.gradle
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/db/remote/ProductDataSource.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/model/Order.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/model/Product.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/repository/ProductRepository.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/product/ProductListAdapter.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/product/ProductListFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/product/ProductListViewModel.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/product/ProductViewModelFactory.kt
  Ipet_seller/app/src/main/res/layout/fragment_product_list.xml
  Ipet_seller/app/src/main/res/layout/item_product_loading.xml
  Ipet_seller/buildSrc/src/main/kotlin/Versions.kt
Labels: Feature

#119 [Feat] 주문/배송 관리 구현 #36
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/db/remote/OrderDataSource.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/repository/OrderRepository.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/home/HomeFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/home/HomeViewModel.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/order/OrderStatusFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/order/OrderStatusViewModel.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/order/OrderStatusViewModelFactory.kt
  Ipet_seller/app/src/main/res/layout/fragment_order_status.xml
Labels: Feature

#120 [Feat] 상품 등록 구현 #78
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/db/remote/ProductDataSource.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/model/Product.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/repository/ProductRepository.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/order/OrderStatusFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/product/ProductListAdapter.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/registration/RegistrationFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/registration/RegistrationViewModel.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/registration/RegistrationViewModelFactory.kt
  Ipet_seller/app/src/main/res/layout/fragment_registration.xml
  Ipet_seller/buildSrc/src/main/kotlin/Versions.kt
Labels: Feature

#121 [Fix] 데이터 형식 변경에 의한 수정
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/model/Order.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/model/Product.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/ProductRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeBestAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeJointAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoViewModel.kt
Labels: Feature

#124 [Feat] 베스트 상품 썸네일 표시 #45
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/ProductRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeBestAdapter.kt
Labels: Feature

#125 [Feat] 공동 구매 제품 클릭 시 정보 표시 #16
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/JointRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeBestAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeJointAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoViewModel.kt
Labels: Feature

#129 [Fix] 썸네일 안나오는 오류 수정 #16
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
Labels: Feature

#133 [Feat] viewPager 도트 추가 및 review 데이터 표시
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/ReviewRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoViewModel.kt
  Ipet_customer/app/src/main/res/layout/fragment_product_info.xml
  Ipet_customer/app/src/main/res/values/colors.xml
Labels: Feature

#136 Fix : conflict Fix
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
Labels: Feature

#137 Fix : 데이터베이스 자료형 수정에 따른 코드 변경 #16
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/model/Joint.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/JointRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/home/HomeJointAdapter.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoViewModel.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductJointAdapter.kt
Labels: FIx

#138 [Feat] 대분류 선택에 따른 소분류 카테고리 다르게 보이도록 구현 #78
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/product/ProductListAdapter.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/registration/RegistrationFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/registration/RegistrationViewModel.kt
Labels: Feature

#142 [Feat] bottomSheet 버튼 클릭 시 DB에 데이터 추가
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/CartRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoViewModel.kt
  Ipet_customer/app/src/main/res/layout/bottomsheet_productinfo.xml
  Ipet_customer/app/src/main/res/layout/fragment_product_info.xml
Labels: Feature

#145 [Fix] 로그인, 회원가입 애니메이션 수정
  Ipet_seller/app/src/main/res/layout/fragment_login.xml
  Ipet_seller/app/src/main/res/layout/fragment_signup.xml
Labels: FIx

#149 [Feat]찜 기능 DB 연결하여 구현 #16
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/model/Heart.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/repository/HeartRepository.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoViewModel.kt
Labels: Feature

#152 [Fix] viewpager 로딩 시 화면이 밀리지 않도록 수정 #16
  Ipet_customer/app/src/main/res/layout/fragment_product_info_view_pager.xml
Labels: FIx

#164 [Feat] 상품 카테고리 표시 #16
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/model/Product.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoViewModel.kt
  Ipet_customer/app/src/main/res/layout/fragment_product_info.xml
Labels: Feature

#166 [Feat] 공동 구매 상품 제품 기간 표시 #16
  Ipet_customer/app/src/main/java/likelion/project/ipet_customer/ui/product/ProductInfoFragment.kt
  Ipet_customer/app/src/main/res/layout/fragment_product_info.xml
Labels: Feature

#168 [Feat] 판매 상품 정보 수정 구현 #147
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/db/remote/ProductDataSource.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/repository/ProductRepository.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/main/MainActivity.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/product/ProductFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/registration/RegistrationFragment.kt
  Ipet_seller/app/src/main/java/likelion/project/ipet_seller/ui/registration/RegistrationViewModel.kt
  Ipet_seller/app/src/main/res/layout/fragment_product.xml
Labels: Feature
